#!/bin/sh

DOCKER_IMAGE_NAME=ngirc
DOCKER_TAG=1.0
DOCKER_CONTAINER_NAME=ngirc

docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG

docker run --name $DOCKER_CONTAINER_NAME \
  -p 6667:6667 \
  $DOCKER_IMAGE_NAME:$DOCKER_TAG
